services:
    mariadb:
        environment:
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb/datas/:/var/lib/mysql/

    postgres:
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "sh -c pg_isready"]
            interval: 10s
            timeout: 3s
            retries: 3
        image: postgres:alpine
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/datas/:/var/lib/postgresql/data

    httpd:
        env_file: ./.env
        build:
            args:
                - uid=${uid}
                - user=${user}
            context: ./httpd/
        environment:
            - ENV=/var/www/.ashrc
        user: ${uid}:${gid}
        volumes:
            - ./httpd/.ashrc:/var/www/.ashrc
            - ./httpd/logs/:/usr/local/apache2/logs/
            - ./tls/server.crt:/usr/local/apache2/key/server.crt
            - ./tls/server.key:/usr/local/apache2/key/server.key
            - ./app/:/var/www/app/
        working_dir: /var/www/

    php:
        env_file: ./.env
        build:
            args:
                - uid=${uid}
                - user=${user}
            context: ./php/
        depends_on:
            mariadb:
                condition: service_healthy
            postgres:
                condition: service_healthy
            httpd:
                condition: service_started
        environment:
            - ENV=/var/www/.ashrc
        user: ${uid}:${gid}
        volumes:
            - ./php/xdebug/:/usr/local/var/xdebug/
            - ./php/.ashrc:/var/www/.ashrc
            - ./app/:/var/www/app/
        working_dir: /var/www/app/

    tls:
        image: alpine/openssl
        profiles:
            - tls
        user: ${uid}:${gid}
        volumes:
            - ./tls/:/tls/
        working_dir: /tls/

networks:
    default:
        name: sf-demo
