Listen *:8000

<VirtualHost *:8000>
    DocumentRoot "/var/www/app/public"

    <Directory "/var/www/app/public">
        Require all granted

        <IfModule mod_rewrite.c>
            Options -MultiViews
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^(.*)$ index.php [QSA,L]
        </IfModule>
    </Directory>

    # optionally disable the RewriteEngine for the asset directories
    # which will allow apache to simply reply with a 404 when files are
    # not found instead of passing the request into the full symfony stack
    <Directory /var/www/app/public/assets>
        <IfModule mod_rewrite.c>
            RewriteEngine Off
        </IfModule>
    </Directory>

    ErrorLog /usr/local/apache2/logs/app_error.log
    CustomLog /usr/local/apache2/logs/app_access.log combined
</VirtualHost>
